### PR TITLE
Minor improvements to Arabic translations

### PR DESCRIPTION
**Pull request by midosvt**

### CODE REVIEW

**Review by AmyrAhmady — APPROVED** [review]

**Comment by RouatbiH** [comment]
@midosvt  في اللغة العربية الفصحى لا توجد كلمة سيرفر
أنت فقط قمت بكتابة الكلمة الإنقليزية كيف تقرأ بالعربية وهذا لا يسمى ترجمة

**Comment by midosvt** [comment]
I know what I am doing, and I am pretty sure anyone that does play video games know what those two are.

**Comment by RouatbiH** [comment]
> I know what I am doing, and I am pretty sure anyone that does play video games know what those two are.

Well, I know the players know what these words mean, but I just wanted to say this because the translation is correct and they can understand it. If the player wants English, he can choose English. There should be no confusion between languages. this is just an opinion.

Have a good day.

**Comment by midosvt** [comment]
the old one was "خادم" which could refer to servant. "سيرفر" is much better. And have a good one you too.

**Pull request merged**
